### ISSUE TITLE
SELECT casing is not working

### ISSUE THREAD

**Issue by runflowcode** [rgalanakis/goless#50]
```
def casing_test2():
    import time
    from datetime import datetime

    def server1(ch):
        time.sleep(6)
        ch.send('from server 1')

    def server2(ch):
        time.sleep(2)
        ch.send('from server 2')

    def main():
        output1 = goless.chan()
        output2 = goless.chan()

        cases = [goless.rcase(output1), goless.rcase(output2)]

        goless.go(server1, output1)
        goless.go(server2, output2)

        # will iterate through all cases, and execute the pick the first available case
        chosen, value = goless.select(cases)

        print(chosen)
        print(value)

    main()

casing_test2()
```

**Outputs:**
_<goless.selecting.rcase object at 0x7fcbacccf390>
from server 1_

<hr/>

The returned result should actually be.
_from server 2_

Can you explain why this is not working as it should ???
server2 would exit first because it is only sleep for 2 seconds, which is faster than server1 6 seconds.

**Comment by rgalanakis** [comment]
`time.sleep` is not set up to be 'cooperative'. It just blocks the current thread, so `server1` function just executes first, waits 6 seconds, then sends. It doesn't compete with server2 because the server2 sleep call isn't made until server1 is done.

It was a mistake to have this in the examples, my bad.

I added a `goless.sleep` shim for this: https://github.com/rgalanakis/goless/pull/51

**Comment by rgalanakis** [comment]
Ok, it turns out there is a good reason I never did this. Sleeping in Stackless is not really supported like it is in gevent.

1) If you try to block on the last tasklet, it errors. I can get around this by using time.sleep if it is the final tasklet.

2) The custom code required for Stackless sleeping requires a long-running tasklet, or a lot of very tricky state management code for cleanup/teardown of the manager. It's possible, but a total pain.

My guess is that most people know exactly what backend they are running under, and use goless for the semantics. So, you should use `gevent.sleep` or use gevents monkey patching over `time.sleep`. If that's a problem, please tell me.

**Comment by runflowcode** [comment]
Thanks for the help.

It was helpful to hear about the way how goless work with the correct sleep timer.
